apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: buildah-
spec:
  taskRef:
    name: buildah
  params:
    - name: IMAGE
      value: 'image-registry.openshift-image-registry.svc:5000/tekton-demo/spring-boot-docker:v1.0.0'
    - name: TLSVERIFY
      value: 'false'
    - name: STORAGE_DRIVER
      value: 'vfs'
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: shared-workspace
  serviceAccountName: tekton-pipeline
