apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-build-push-deploy
spec:
  params:
  - name: event-headers
    type: string
    description: "The event headers"
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: build-push-task
    taskRef:
      name: task-build-push
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: docker-image
        resource: docker-image
  - name: image-scan-task
    taskRef:
      name: task-image-scan
    runAfter: [build-push-task]
    resources:
      inputs:
      - name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image  
  - name: deploy-task
    taskRef:
      name: task-deploy
    runAfter: [image-scan-task]
    resources:
      inputs:
      - name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image
