apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-pipeline
  namespace: default

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-pipeline
  namespace: default
rules:
- apiGroups: ["extensions", "apps", "", "appsody.dev"]
  resources: ["services", "deployments", "pods", "appsodyapplications"]
  verbs: ["get", "create", "update", "patch", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-pipeline
subjects:
- kind: ServiceAccount
  name: sa-pipeline
  namespace: default