apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipeline-role
rules:
- apiGroups: [""]
  resources: ["deployments", "services", "pods"]
  verbs: ["get", "list", "create"]

