apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipeline-role-binding
  namespace: tekton-demo
subjects:
- kind: ServiceAccount
  name: tekton-pipeline
  namespace: tekton-demo
roleRef:
  kind: ClusterRole
  name: tekton-pipeline-role
  apiGroup: rbac.authorization.k8s.io

