apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-event-listener
spec:
  triggers:
    - name: github-listener
      bindings:
      - ref: tekton-trigger-binding
      template:
        ref: tekton-trigger-template
